Repository redbadger/continous-compliance, pull requests merged in 2021-04, with the labels that each got.

#21 Create a GitHub action that print Hello on Dracula
  .gitignore
  .nvmrc
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package.json
  readme.md
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: feature :sparkles:

#22 Copy test results into a compliance folder
  .eslintignore
  .eslintrc.json
  .github/workflows/test.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierignore
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  jest.config.js
  package.json
  src/index.ts
  src/shared/constants.ts
  src/steps/copy-test-folder-into-compliance/index.test.ts
  src/steps/copy-test-folder-into-compliance/index.ts
  src/steps/create-compliance-folder/index.test.ts
  src/steps/create-compliance-folder/index.ts
  yarn.lock
Labels: feature :sparkles:

#23 Compress compliance folder
  .eslintrc.json
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  jest.config.js
  package.json
  readme.md
  scripts/create-tag.sh
  scripts/delete-tag.sh
  src/index.ts
  src/steps/compress-compliance-folder/index.test.ts
  src/steps/compress-compliance-folder/index.ts
  src/steps/copy-test-folder-into-compliance/index.test.ts
  src/steps/copy-test-folder-into-compliance/index.ts
  src/steps/create-compliance-folder/index.test.ts
  src/steps/create-compliance-folder/index.ts
  src/steps/readme.md
  yarn.lock
Labels: feature :sparkles:

#26 Copy docs folder
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  src/index.ts
  src/steps/copy-doc-folder-into-compliance/index.test.ts
  src/steps/copy-doc-folder-into-compliance/index.ts
  src/steps/readme.md
Labels: feature :sparkles:

#28 Docs docs baby
  readme.md
  src/steps/readme.md
Labels: feature :sparkles:

#30 Add dependabot config
  .github/dependabot.yml
Labels: dependabot 🤖, feature :sparkles:

#47 License
  license.md
Labels: enhancement

#48 Quote
  readme.md
Labels: documentation

#49 Readme update
  readme.md
Labels: documentation
